name: CI

on:
  push:
    branches: [main, master, develop, develop_keypoint_orientation_sfm]
  pull_request:
    branches: [main, master, develop, develop_keypoint_orientation_sfm]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-tests:
    name: Build and Test on Windows
    runs-on: windows-latest
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v2

      - name: Create Build Directory
        run: |
          if (-Not (Test-Path -Path ".\build")) {
            New-Item -ItemType Directory -Path .\build
          }
        shell: pwsh

      - name: Git Submodule Update
        run: |
          git submodule update -i
        shell: pwsh

      - name: Configure CMake
        working-directory: ./build
        run: |
          cmake ..\src `
          -DOpenMVG_BUILD_TESTS=ON `
          -DOpenMVG_BUILD_EXAMPLES=ON `
          -DOpenMVG_BUILD_SOFTWARES=ON `
          -DSCHUR_SPECIALIZATIONS=OFF
        shell: pwsh

      - name: Build
        working-directory: ./build
        run: |
          cmake --build . --config Release --parallel 4
        shell: pwsh

      - name: Run Unit Tests
        working-directory: ./build
        run: |
          ctest -j$(Get-ComputerInfo | Select-Object -ExpandProperty NumberOfLogicalProcessors) --build-config Release
        shell: pwsh
