name: CI

on:
  push:
    branches: [main, master, develop, develop_keypoint_orientation_sfm]
  pull_request:
    branches: [main, master, develop, develop_keypoint_orientation_sfm]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-tests:
    name: Build on Windows
    runs-on: windows-latest
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v2

      - name: Git submodule
        run: |
          mkdir ./build
          git submodule update -i

      - name: Configure CMake
        working-directory: ./build
        run: |
          cmake ../src ^
          -DOpenMVG_BUILD_TESTS=ON ^
          -DOpenMVG_BUILD_EXAMPLES=ON ^
          -DOpenMVG_BUILD_SOFTWARES=ON ^
          -DSCHUR_SPECIALIZATIONS=OFF
        shell: pwsh

      - name: Build
        working-directory: ./build
        run: |
          cmake --build . --config Release --parallel 4
        shell: pwsh

      - name: Unit Tests
        working-directory: ./build
        run: |
          ctest -j$(Get-ComputerInfo | Select-Object -ExpandProperty NumberOfLogicalProcessors) --build-config Release
        shell: pwsh
