name: Build OpenMVG on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: twxs/cmake-action@v2
      with:
        cmake-version: '3.23'

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Install Dependencies
      run: |
        choco install git cmake
        # Optionally install other dependencies required for OpenMVG

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 .. # Adjust generator and architecture if needed

    - name: Build OpenMVG
      run: |
        cd build
        msbuild openMVG.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openMVG-build
        path: build/Release
